// Add templated overrides
// This uses dockerize template, i.e. Go syntax
// Note that the substitutions will be done at runtime, in the compiled .js files, NOT at compile time!

// `.env.ts` is generated by the `npm run env` command
import env from "./.env";

export const environment = {
  production: true,
  version: env.mifos_x_version,
  fineractPlatformTenantId: "<YJ .Env.TENANT_ID YJ>",
  baseApiUrl: "<YJ .Env.SERVER_URL YJ>",
  allowServerSwitch: false,
  apiProvider: "/fineract-provider/api",
  apiVersion: "/v1",
  serverUrl: "",
  oauth: {
    enabled: false, // For connecting to Mifos X using OAuth2 Authentication change the value to true
    serverUrl: "",
  },
  defaultLanguage: "en-US",
  supportedLanguages: ["en-US", "fr-FR"],
};

// Server URL
environment.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}${environment.apiVersion}`;
environment.oauth.serverUrl = `${environment.baseApiUrl}${environment.apiProvider}`;
